name: task1
on:
 issues:
  types:
   - closed
jobs:
 log_user:
  runs-on: ubuntu-latest
   steps:
    - name: Update README
     uses: theboi/github-update-readme@v1.0
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
	       header: "Latest issue closed by **${{ github.actor }}**".
	
